# Local Network Deployment Configuration
# This configuration disables SSL/ACME and uses local hostnames

services:
  # Traefik - Local Configuration
  traefik:
    image: traefik:v3.0
    container_name: homelab-traefik-local
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8080
      # Skip ACME for local deployment
      - --global.sendAnonymousUsage=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Enable API port for local access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/local:/etc/traefik/dynamic:ro
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`) || Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  # Docker Socket Proxy
  socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    container_name: homelab-socket-proxy-local
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      SERVICES: 1
      TASKS: 1
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  # Portainer
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: homelab-portainer-local
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`) || Host(`localhost`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Whoami - Test Service
  whoami:
    image: traefik/whoami:v1.10.1
    container_name: homelab-whoami-local
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`) || Host(`test.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    external: true
