# static config
api:
  dashboard: true
  insecure: false

# redirect http -> https
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default@file
  # Optional: SSH passthrough for git operations
  # ssh:
  #   address: ":2222"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
  docker:
    endpoint: "tcp://socket-proxy:2375"
    network: "docker-traefik-apps_proxy"
    exposedByDefault: false
    watch: true

# let's encrypt via cloudflare dns challenge
certificatesResolvers:
  letsencrypt:
    acme:
      email: "x@xuper.fun"
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      # RECOMMENDED: pre-provision wildcard certificate
      # domains:
      #   - main: "${DOMAIN}"
      #     sans:
      #       - "*.${DOMAIN}"

# Better logging for troubleshooting
log:
  level: INFO
  format: json

accessLog:
  format: json
  filters:
    # Don't log health checks and static assets
    statusCodes: ["400-499", "500-599"]

# Enable metrics (optional - for monitoring)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Improve performance
serversTransport:
  insecureSkipVerify: false

ping:
  entryPoint: "traefik"
